options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Use a specific version of the terraform image for consistent builds
  - name: 'hashicorp/terraform:1.8.2'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        # The GCS backend needs credentials to initialize.
        # Cloud Build's service account needs "Storage Admin" on the bucket,
        # or "Storage Object Admin" on the objects inside the prefix.
        terraform init

  # This step runs on all branches to allow for plan validation
  - name: 'hashicorp/terraform:1.8.2'
    entrypoint: 'terraform'
    args: ['plan', '-out=tfplan']

  # This step only runs on the 'usecase-2' branch
  - name: 'hashicorp/terraform:1.8.2'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        if [ "$BRANCH_NAME" = "usecase-2" ]; then
          echo "Applying changes on master branch."
          terraform apply -auto-approve tfplan
        else
          echo "Skipping apply: not on usecase-2 branch."
        fi
 
